# -*- coding: utf-8 -*-
"""ShreyaJoshi_Worksheet -1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knBBR-Lspitk0duj8JZDRiqPtH1gYyLB
"""

import numpy as np

empty_array = np.empty((2,2))
print(empty_array)

ones_array = np.ones((4,2))
print(ones_array)

full_array = np.full((3,3), 7)
print(full_array)

arr = np.array([[1,2,3],[4,5,6]])
zeros_like_arr = np.zeros_like(arr)
print(zeros_like_arr)

arr = np.array([[1,2,3],[4,5,6]])
zeros_like_arr = np.zeros_like(arr)
print(zeros_like_arr)

new_list = [1,2,3,4]
array_from_list = np.array(new_list)
print(array_from_list)

import numpy as np
arr_range = np.arange(10, 50)
print(arr_range)

matrix_3x3 = np.arange(9).reshape(3,3)
print(matrix_3x3)

identity_matrix = np.eye(3)
print(identity_matrix)

random_array = np.random.random(30)
print("Mean:", random_array.mean())

rand_10x10 = np.random.random((10,10))
print("Min:", rand_10x10.min())
print("Max:", rand_10x10.max())

zero_array = np.zeros(10, dtype=int)
zero_array[4] = 1
print(zero_array)

arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

border_array = np.ones((5,5), dtype=int)
border_array[1:-1, 1:-1] = 0
print(border_array)

checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("x + y:\n", np.add(x,y))

print("x - y:\n", np.subtract(x,y))

print("x * 3:\n", x * 3)

print("Square of x:\n", np.square(x))

print("v · w:", np.dot(v,w))
print("x · v:\n", np.dot(x,v))
print("x · y:\n", np.dot(x,y))

concat_xy = np.concatenate((x,y), axis=0)
print("Concatenate x and y (rows):\n", concat_xy)

concat_vw = np.vstack((v,w))
print("Concatenate v and w (columns):\n", concat_vw)

try:
    concat_xv = np.concatenate((x,v))
    print(concat_xv)
except ValueError as e:
    print("Error:", e)

import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print("A * A^-1:\n", result)

AB = np.dot(A,B)
BA = np.dot(B,A)
print("AB:\n", AB)
print("BA:\n", BA)

AB = np.dot(A,B)
lhs = AB.T
rhs = np.dot(B.T, A.T)
print("LHS (AB)^T:\n", lhs)
print("RHS B^T A^T:\n", rhs)

A_sys = np.array([[2,-3,1],
                  [1,-1,2],
                  [3, 1,-1]])
B_sys = np.array([-1,-3,9])
A_inv_sys = np.linalg.inv(A_sys)
X = np.dot(A_inv_sys, B_sys)
print("Solution [x, y, z]:", X)

import time

list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()
list_add = [a+b for a,b in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

import numpy as np

arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end - start)

start = time.time()
list_mul = [a*b for a,b in zip(list1, list2)]
end = time.time()
print("Python list multiplication time:", end - start)

start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end - start)

start = time.time()
dot_list = sum(a*b for a,b in zip(list1, list2))
end = time.time()
print("Python list dot product time:", end - start)

start = time.time()
dot_arr = np.dot(arr1, arr2)
end = time.time()
print("NumPy array dot product time:", end - start)

list_matrix1 = [[i for i in range(1000)] for _ in range(1000)]
list_matrix2 = [[i for i in range(1000)] for _ in range(1000)]

start = time.time()
result_matrix = [[sum(a*b for a,b in zip(row,col))
                  for col in zip(*list_matrix2)]
                  for row in list_matrix1]
end = time.time()
print("Python list matrix multiplication time:", end - start)

arr_matrix1 = np.arange(1000000).reshape(1000,1000)
arr_matrix2 = np.arange(1000000).reshape(1000,1000)

start = time.time()
result_np = np.dot(arr_matrix1, arr_matrix2)
end = time.time()
print("NumPy matrix multiplication time:", end - start)